CREATE DATABASE CRUD_COURSES;

USE CRUD_COURSES;

CREATE TABLE COURSE(
    COURSE_ID INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY(COURSE_ID),
    FACULTY_ID VARCHAR(10) NOT NULL,
    COURSE_CODE VARCHAR(8) NOT NULL,
    COURSE_NAME VARCHAR(64) NOT NULL,
    UNIQUE(FACULTY_ID, COURSE_CODE),
    PROFESSOR_FULL_NAME VARCHAR(128) NOT NULL,
    CLASSROOM_NUMBER VARCHAR(16) NOT NULL,
    CREDITS VARCHAR(16) NOT NULL
);

CREATE TABLE STUDENT(
    STUDENT_ID INT AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (STUDENT_ID),
    STUDENT_ID_NUMBER VARCHAR(10) UNIQUE NOT NULL,
    NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(128) NOT NULL,
    EMAIL VARCHAR(128) UNIQUE NOT NULL
);

CREATE TABLE COURSE_STUDENT(
    STUDENT_ID INT NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    COURSE_ID INT NOT NULL,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
    PRIMARY KEY(STUDENT_ID, COURSE_ID)
);

